### ISSUE TITLE
Particle not showing as before in project scene

### ISSUE THREAD

**Issue by jymen** [UnderwaterApps/overlap2d#108]
Dragging a particle on project scene shows now a kind of 'red icon' inside the scene instead of the particle itself (see attached screen shot )
![screen shot 2015-07-22 at 15 00 24](https://cloud.githubusercontent.com/assets/644653/8828626/74031aaa-3093-11e5-87aa-29b593121446.png)

**Comment by azakhary** [comment]
I think particle effect is not showing because it is not continuous effect, (e.g. it repeats only once) so maybe first run goes unnoticed because of a lag, and then it just does not do it's thing again.

The orange icon is a "particle effect" icon, it is always there so that you can easily find where to drag drop the effect, because sometimes there is no visible bounds to it. And you do not know where is it's local zero coordinate.

Given that, I propose to add functionality to editor, to force "continuous" on all particles while in sandbox, but without saving that data. This probably can be done even in TextureManager or Editor's ResourceManager, so that when it is asked for particle effect, before "giving it out" it will modify it by setting to continuous mode.

Let me know if this makes sense.

**Comment by jymen** [comment]
One of the particle is effectively not continuous 
==> I think forcing continuous is the best solution since the designer will just need to see how the particle look in context + perhaps having a a show/hide checkbox to make it disapear on demand would also help then ...

the second one is ... But there is a Pixel per meter which is to high and makes the sprite not visible somewhere ==> I'll have a deeper look on this one and will come back

**Comment by azakhary** [comment]
Oh rrright, it totally is pixel per world unit thing that makes it invisible. I probably forgot adjusting PE's will add that.

**Comment by azakhary** [comment]
Fixed this with latest push. you will need to update both runtime and the editor.
Thanks for reporting!
