### ISSUE TITLE
item scaling not undoable/redoable

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#145]

**Comment by azakhary** [comment]
Should be easy to fix, need to change id it's done through a Command or not.

**Comment by kutoman** [comment]
ok I will check that

**Comment by kutoman** [comment]
do I have to create a new command class, or is there already one? I still need to get used to the new architecture :)

**Comment by azakhary** [comment]
I think the right way would be to create new command that looks like ItemsMoveTo  but will be something like ItemTransformComand will do basically the same but for one item and for scale, rotation instead of x, y  (or width height if it's nine patch) and then TransdormTool should be modified to use that command instead of directly accessing the Component

**Comment by kutoman** [comment]
ok got it

**Comment by azakhary** [comment]
Thanks @kutoman ! Merged.
