### ISSUE TITLE
items forever hidden

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#216]
If I hide a layer, the items get naturally hidden. But if I unhide the layer, the items stay hidden

**Comment by kutoman** [comment]
the events for unlocking and unhiding seem to be missing now. I'll fix that

**Comment by azakhary** [comment]
oh.. wait but this lines were important.
I had this bug:
when item was invisible but layer visible - item was becoming visible.
So I added this lines, to make sure item can become invisible even if i's on visible layer.
So runtime is doing correct with this lines. this bug should be fixed in editor instead.

**Comment by kutoman** [comment]
I see. When I first saw that line, I divined that purpose you mentioned, but then I thought that yet it's not possible to set an item's individual visibility in the editor (maybe I'm wrong), thus I removed it.

**Comment by azakhary** [comment]
So I propose the following, this has to be changed, so that visibility of individual item has nothing to do with layer visibility, and that runtime works like that, and editor too. It's a lot of changes so I'll try to take over this one today if you do not mind.

**Comment by azakhary** [comment]
Fixed in latest runtime push

**Comment by kutoman** [comment]
yeah sure, I'm busy these days :)
