### ISSUE TITLE
Creating Unit Tests

### ISSUE THREAD

**Issue by azakhary** [UnderwaterApps/overlap2d#231]

**Comment by htynkn** [comment]
I think we can start with some small test. Because the project is not test-driven-development, some code maybe hard to test, but with the powerful test tools like mockito and powermock, we can at least make the unit tests work.

And there is another thing I'm thinking. You know we can have functional test for web site, but I don't know is that possible for us to create some test to test the project. 
For example, some test code for 
`clicking the create project option`, then `show a dialog with title "Create New Project"`, the `enter the project name` and `click create button`, then we should have a project file in that directory.

**Comment by azakhary** [comment]
To be honest I never worked with mockito or powermock, I guess I have to do some reading on this. But yes, what you say makes sense.

As for the website, actually it is not in github. Which we can fix of course, I can put website to the github, open source it, and have deployment system for it. Considering we will have plugin store, that is worth doing.
