### ISSUE TITLE
Editor does not import 9patches (Linux)

### ISSUE THREAD

**Issue by Nitheism** [UnderwaterApps/overlap2d#342]
I tried to import 9patches, they are named by the rules, but they don't appear in images or anywhere so they are not imported I tried to make new project to see if it will work but it doesn't still can't import them.

**Comment by azakhary** [comment]
can you share a nine patch file you are trying to import.?

**Comment by Nitheism** [comment]
![coin 9](https://cloud.githubusercontent.com/assets/8667399/12232316/8669902e-b866-11e5-82b1-41e8dd1caa29.png)
and now I realized I can't import anything

**Comment by azakhary** [comment]
not sure about import anything part, but, this 9patch has some red lines in it. This issue was reported before. 
Having red lines is not compliant with libGDX NinePatch class. What tool do you use for 9 patch making?

You have to valid options. 
Either use nine patch tool that is supplied with android SDK. Or use overlap2D built in 9patch editor.
For later case, just import regular image, and then right click, convert to nine patch.

**Comment by Nitheism** [comment]
I used the android asset studio

**Comment by azakhary** [comment]
Got it. So yeah, if you use the tools I mentioned things should be fine for you.

Otherwise, if interested, here is the original libGDX issue: https://github.com/libgdx/libgdx/pull/3643#issuecomment-164906802
You can discuss this with them if it makes sense, as this issue is related to libGDX more then Overlap2D

**Comment by Nitheism** [comment]
actually I don't have convert to 9patch

**Comment by azakhary** [comment]
are you using latest editor from the website?

**Comment by Nitheism** [comment]
yes

**Comment by azakhary** [comment]
Let me just put the exact steps here in case you do something else:
1) Import an image
2) Drag drop that image on the scene
3) Right click on that image that is on the scene (not one in your asset list)
4) There should be convert to nine patch option in drop down.

**Comment by Nitheism** [comment]
Yes I do that I import an image, drop it into the scene then right click but doesn't have it. 
![screenshot from 2016-01-11 14-16-07](https://cloud.githubusercontent.com/assets/8667399/12233210/f21624de-b86d-11e5-8e9b-638a7e338304.png) 
here is a pic

**Comment by azakhary** [comment]
Wow... that's weird. I start to think that entire plugin mechanism is not working on Linux. Because on WIndows it's fine.  Does your window panel look like this? If no then it's plugins not loading on Linux, which sucks.
I just don't have a linux machine right now to debug that. But if that's the case we need to have an open issue for that case.

![kkk](https://cloud.githubusercontent.com/assets/2115888/12233542/0180a3fa-b881-11e5-9bc4-91fdab26c906.png)

**Comment by Nitheism** [comment]
No it doesnt, it just has the first 2 things

**Comment by azakhary** [comment]
So it's the plugin things. Sad :( Let me open an issue for that, but I can't fix it now, as I don't have Linux for this moment.

**Comment by Nitheism** [comment]
Okey no problem I can switch to my windows to do the work, the impotant is that we found the problem with lunix good luck and tnx

**Comment by azakhary** [comment]
Thanks for pointing it out!

**Comment by kondinskis** [comment]
Try running from terminal, not by double clicking.
java -jar overlap2d.jar. Fixes the following problem on linux. Tested on Ubuntu 16.04 works fine.
